# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DictionaryDesign2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DictionaryDesign2
    pod 'Alamofire', '~> 5.5'

  target 'DictionaryDesign2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DictionaryDesign2UITests' do
    # Pods for testing
  end

end
