# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieAppDesign' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieAppDesign
    pod 'Firebase/Core'
    pod  'Firebase/Database'

  target 'MovieAppDesignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppDesignUITests' do
    # Pods for testing
  end

end
